version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn canteen_ordering_sys.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-2k8svw_k2ylfsr##^cjh9^33m=_v+s%c&&3ge149i&&-spx+-8
      - DATABASE_NAME=cos-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=cos-pass
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    env_file:
      - .env  # Optional: to store sensitive information securely

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: cos-db
      MYSQL_USER: user
      MYSQL_PASSWORD: cos-pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

volumes:
  mysql_data:
