# Generated by Django 4.2 on 2024-11-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_alter_fooditem_description_alter_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
