# Generated by Django 4.2 on 2024-11-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_fooditem_is_in_stock_fooditem_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='description',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='foodchoice',
            field=models.CharField(choices=[('snack', 'Snacks'), ('hot_drinks', 'Hot Drinks'), ('beverages', 'Beverages'), ('lunch', 'Lunch')], default='snack', max_length=20),
        ),
    ]
