# Generated by Django 4.2 on 2024-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cart_is_paid_orders_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=50),
        ),
    ]
