# Generated by Django 4.2 on 2024-10-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orders_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=50),
        ),
    ]
