# Generated by Django 4.2 on 2024-11-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
