# Generated by Django 4.2 on 2024-11-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_fooditem_is_in_stock_fooditem_stock_quantity'),
        ('order', '0008_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='food_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canteen.fooditem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
