# Generated by Django 4.2 on 2024-11-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_orders_food_item_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
